favorite_animal = input("What is your favorite animal?:\n ")
animal_food = input("What food does the animal eat?:\n ")
animal_live = input("Where does your animal live?:\n ")
animal_color = input("What color is the animal?:\n ")
animal_fact = input("What's a fact about the animal?:\n ")
animal_like = input("Why do you like the animal?:\n ")
print("Your favorite animal is a "+favorite_animal + " and your animal eats "+animal_food + ". Your animal lives in "+animal_live + " and your animal is "+ animal_color + ". A fact about the animal is "+animal_fact + " and you like the animal because "+animal_like +".")
