favorite_animal = input("What is your favorite animal?: ")
animal_food = input("What food does the animal eat?: ")
animal_live = input("Where does your animal live?: ")
animal_color = input("What color is the animal?: ")
animal_fact = input("What's a fact about the animal?: ")
animal_like = input("Why do you like the animal?: ")
print("Your favorite animal is "+favorite_animal)
print("and your animal eat "+animal_food)
print(". Your animal lives in "+animal_live)
print(" and your animal is "+animal_color)
print(". A fact about the animal is "+animal_fact)
print(" and you like the animal because "+animal_like)
